travis:
  secure:
    BINSTAR_TOKEN: nhnPE+B6l2JyTE6fRVygFFMPaF6Rhg4P+vc2mlkVm5wmuRkBTbB98iiqnUnnOFHv8NZR+GQq4y6jlQ4EnBFddwrMxYDYmGSg+A94y2mHmIq7HrXvtYQ8q85DYfr2g6ckTJeQH69JIdN0TtZ2FTeM3XveaCwL89FldLi+oMsSQ58XDgO+rCCYZC0ojvc5yyRolXJvCkp2FQD3opgzD3vwT8QcM+Gsjsn1yvj6X4xM4GlmBAoNTJWTts0c08wvBst4KX/53UVlmO/W3uHcJ+LhMXXYUKNMjS5onRR9ht2xS+uQIMXXlMTQL1MTPpt3Am18qtdDKJxl21KEuxe1zfzAz3BziLIgQs53j24zR/TB3pC5Sx/9CdK0vZ8VpulR94J9YVr9CbM62Pe8ikGwb9Eiq93HBK0E1KmSefHTFei8x6wGfVtRqvoNZGjkZyX3tVgNqrTMmEyuYv1FqDHKCG2FfEGfJ4aqqhO1YGyqr4/w2HmRMh3ZCsrbtg0CfSIvjV80dMjbHon4wH97sRQC3bGRyRkriIh7Z8NgaQUvCdg7jobafFKmeYsb2L+Tndk71xnt8BZ5T7e0GEqBcCyxz1ZsKpcgUeMyd5hZjLwLtQqO1bYc4vrkBgdzDH+cbiRGR4sZlG9q4OmKRiBEoAckaVU6z75y+IPePNUOg9Wk/kSyr4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
